### ISSUE TITLE
ForceSimulation

### ISSUE THREAD

**Issue by ozpos** [taw/opal-d3#3] opened 2018-04-23 20:18 UTC
Hi, Thank you for sharing your code.  Not really an issue but a request for suggestions. 

I am trying to create a simple force directed menu in ruby with click event listeners on nodes and links.
I have built and can run your examples under rubymine2018.1
My java skills are poor, and I am struggling to create an example (and supporting classes) to access the d3.forceSimulation API.

Could you please tell me (if it is not too stupid a question) which of the existing modules most closely matches that of d3-force. e.g. passing an array of nodes to d3.forceSimulation and has similar sub-function calls like forceCenter in this case ?

many thanks in advance,
ozpos

**Comment by taw** [comment] 2018-04-24 21:41
Well, as README says, "About 60% of D3 APIs are implemented."

I never got to the forces API, so unless you feel like implementing wrappers yourself, or mixing ruby with js, that won't currently work.

**Comment by ozpos** [comment] 2018-04-25 08:09
Hi, taw thanks for the reply.  Yes I am willing to implement as much as I can, just a v steep learning curve.  I have 30 y+ exp in Assembler C and Ruby amongst others so my brain is not as nimble as it used to be.

I have created a start_trek_voyager_force example based on your s t v and it works as it should with the aim of gradually implementing d3-force wrapper. I have started to wrap D3.simulate but have not got it to spit anything out yet. (D3 is new to me also).

I do not yet fully understanding the basics of function call syntax, parameter handling and return values (which is unfortunately all you need to know to wrap a lib and the reason why I asked if an existing example contained similar calls to that of d3-force).

Any help would be greatly appreciated.

**Comment by ozpos** [comment] 2018-04-27 20:37
Hi, I have hit a bit of a wall.
I created a demo app based on start trek app and all was ok so my file structure and environment must be ok also. To try and pin things down and allow anyone to chip in with some knowledge I am using this https://bl.ocks.org/rofrischmann/ef51753ff4ac2b7d6ebdb04ac182b5c7 minimal force demo
as a working js target for discussion purposes.

So when I rip out the star trek data and demo ruby code and replace it with ForceSimulation and ForceLink wrapper classes and what I think should be the right ruby code for this new force demo I get nothing (no surprise there then).

At least now I can show some code and ask a question or two.

Are my wrapper classes on the right lines and what is missing/wrong ?
# Data
```
STVFNodes = [
    { "id": "mammal", "group": 0, "label": "Mammals", "level": 1 },
    ...
    { "id": "pike"  , "group": 2, "label": "Pikes"  , "level": 2 }
                       ].map{|o| OpenStruct.new(o)}
STVFLinks = [
    { "target": "mammal", "source": "dog" , "strength": 0.7 },
    ...
    { "target": "pike"  , "source": "cat" , "strength": 0.1 }
                      ].map{|o| OpenStruct.new(o)}
```
# force_simulation.rb
```
module D3
  class ForceSimulation
    include D3::Native

    def call(data)
      @native.call(data)
    end

      #No idea what else I should put here
  end

  class << self
    def force_simulation
      D3::ForceSimulation.new( @d3.JS.forceSimulation())
    end
    def force(name,value1, value2)
      if name == "charge"
        self.class.new @d3.JS.forceManyBody().strength(value1)
      elsif name == "center"
        self.class.new @d3.JS.forceCenter(value1,value2)
      elsif name == "link"
        self.class.new @d3.JS.forceLink(value1)
      end
      # D3::ForceSimulation
    end

   def nodes(data)
      self.class.new @native.JS.nodes(data)
    end
  end
end
```
# force_link.rb
```
module D3
  class ForceLink
    include D3::Native
    #  No idea what else I should put here
    def call(data)
      @native.call(data)
    end
  end

  class << self
    def force_link
      D3::ForceLink.new( @d3.JS.forceLink())
    end
  end
end
```
# Demo ruby app
```
require "opal"
require "opal-d3"
require "data/star_trek_voyager_force"

getNodeColor = proc do |n|
  n.level == 1 ? 'red' : 'gray'
end

svg = D3.select("#visualization")
          .attr("height", "600px")
          .attr("width", "100%")
width = svg.style("width").to_i

getid = proc do |node|
  node.id
end

getstrength = proc do |node|
  node.strength
end

linkforce = D3.linkForce()
    .id(&getid(n))
    .strength(&getstrength(n))

simulation = D3.force_simulation()
    .force('link',linkForce)
    .force('charge', -120)
    .force('center', width / 2, 300)

linkElements = svg.append("g")
                   .attr("class", "links")
                   .selectAll("line")
                   .data(STVFLinks)
                   .enter().append("line")
                   .attr("stroke-width", 1)
                   .attr("stroke", "rgba(50, 50, 50, 0.2)")

nodeElements = svg.append("g")
                   .attr("class", "nodes")
                   .selectAll("circle")
                   .data(STVFNodes)
                   .enter().append("circle")
                   .attr("r", 10)
                   .attr("fill", "none")  # &getNodeColor)

textElements = svg.append("g")
                   .attr("class", "texts")
                   .selectAll("text")
                   .data(STVFNodes)
                   .enter().append("text")
                   .text(function (node) { return  node.label })
                   .attr("font-size", 15)
                   .attr("dx", 15)
                   .attr("dy", 4)
# No idea how to code this ->
# simulation.nodes(nodes).on('tick', () => {
#   nodeElements
#     .attr('cx', function (node) { return node.x })
#     .attr('cy', function (node) { return node.y })
#   textElements
#     .attr('x', function (node) { return node.x })
#     .attr('y', function (node) { return node.y })
#   linkElements
#     .attr('x1', function (link) { return link.source.x })
#     .attr('y1', function (link) { return link.source.y })
#     .attr('x2', function (link) { return link.target.x })
#     .attr('y2', function (link) { return link.target.y })
# })

simulation.force("link",STVFLinks)
```

Many thanks in advance.

**Comment by ozpos** [comment] 2018-05-02 20:53
Hi all, Please help me get started.  I cannot contribute without some help.

I have forked and created a feature branch. https://github.com/ozpos/opal-d3/tree/d3-force

Any ideas what is wrong with this simple/minimal force wrapper?

**Comment by taw** [comment] 2018-05-02 20:54
Hi,

Sorry for the delay. I'll check it on the weekend. Not much time right now unfortunately.

**Comment by ozpos** [comment] 2018-05-03 07:21
That is great thank you.

**Comment by taw** [comment] 2018-05-07 18:48
OK, looking at this now.

**Comment by taw** [comment] 2018-05-07 20:49
I added some code and an example of it working.

It's quite problematic, as it has to drop to native objects far too much.

The problem is that we want to use Opal objects (possibly wrapped around native objects), but D3 force simulation really wants native JS objects and it wants to set `x` / `y` on them.

`D3::ForceSimulation#nodes` / `D3::Force#links` could wrap/unwrap them, but that doesn't actually help, as original objects will be unaware of values d3-force writes back.

There's a bunch of approaches it could take from here:

* create some `D3::ForceNode` and `D3::ForceLink` classes which are aware of this whole situation, and force caller to only use those, not anything caller wants. That's probably fastest way to get it to some sensible situation.
* ES6 Proxies - that's one way Opal could interoperate with js better. Probably best to wait for Opal to do that. Will never run in old browsers, but that's less of a problem nowadays.
* patch our copy of d3-force - it's just a bunch of functions, and only the parts which write back to nodes / links need fixing.

**Comment by taw** [comment] 2018-05-07 20:51
Relevant files:
* [`force.rb`](https://github.com/taw/opal-d3/blob/master/lib/opal/d3/force.rb)
* [`eu_force_graph.rb`](https://github.com/taw/opal-d3/blob/master/demo/app/eu_force_graph.rb)

Sorry for the delay. As you can see it's not exactly trivial stuff.

**Comment by ozpos** [comment] 2018-05-08 12:14
No probs. Thank you, I did not expect a working example. I will try and expand the complexity with additional demos.

(1) If the nodes contained a 'level' data value how would you set the fill colour given the following js ?
``
function getNodeColor(node) {
  return node.level === 1 ? 'red' : 'gray'
}
var nodeElements = svg.append("g")
  .attr("class", "nodes")
  .selectAll("circle")
  .data(nodes)
  .enter().append("circle")
    .attr("r", 10)
    .attr("fill", getNodeColor)

(2) Could you please explain a little further why you say the 'Force demo. This is not good code' ?

Many many thanks for getting me started, hopefully I can give some back.

**Comment by taw** [comment] 2018-05-08 18:39
The code is not good, as it doesn't work with ruby objects, it works with js native objects, which need backticks everywhere. In other d3 demos you can use nice pure ruby interfaces.

It works at least, but it should really get improved to the point where none of this native stuff is needed for just a regular demo.

For your question, something like this I guess (if `nodes` got mapped to `js` objects so need backticks to access):

```
node_elements = svg.append("g")
  .attr("class", "nodes")
  .select_all("circle")
  .data(nodes)
  .enter().append("circle")
  .attr("r", 10)
  .attr("fill"){|node| `node.level === 1` ? "red" : "gray"  }
```

**Comment by ozpos** [comment] 2018-05-08 19:17
What would a none native version of
`` .attr("fill"){|node| `node.level === 1` ? "red" : "gray"  }
look like ?

**Comment by taw** [comment] 2018-05-26 09:09
With ruby code it would just be something like `.attr("fill"){|node| node[:level] == 1 ? "red" : "gray" }`

**Comment by taw** [comment] 2020-11-12 13:30
I'll just close this. If you have nice working examples, feel free to PR.

**Closed as completed by taw** 2020-11-12 13:30 UTC
